<?php

    $ua = array(
        'bid_sucess' => "Ставка прийнята успішно",
        'bid_failed' => "Ваша ставка нижча за актуальну",
        'site_title_1' => "Розігруємо славнозвісну марку з підписом автора",
        'site_title_2' => "Прийміть участь у благодійному аукціоні. Допоможіть ЗСУ і отримайте марку з підписом автора славнозвісної фрази. Всі отримані кошти підуть на покупку",
        'site_title_3' => "реанімобіля для медичної служби військової частини А7030.",
        'max_bid' => "Максимальна ставка: ",
        'make_a_bid' => "  Підняти ставку",
        'bid' => "ставки",
        'bids' => "ставок",
        'bids_quont' => " вже зроблено!",
        'timer_1' => "Благодійний аукціон закінчується через:",
        'timer_2' => " днів",
        'currency' => "грн.",
        'history_1' => "Добродій ",
        'hide' => "(прихований) ",
        'history_2' => " підвищив ставку станом на: ",
        'show_all' => "Переглянути всі ставки",
        'for_what_1' => "Всі кошти від благодійного аукціону будуть переразовані на реаніиобіль для медичної служби військової частини А7030 🙏 ❤️.",
        'for_what_2' => "<p>Щодня російська орда ранить та вбиває сотні наших співвітчизників.</p><p>Медична служба рятує не лише військових, а і місцевих жителів.</p><p>Своєчасна евакуація з поля бою та надання першої медичної допомоги рятує життя.</p><p>Медики – це ангели охоронці наших хлопців на полі бою.</p>",
        'footer_1' => "Благодійний аукціон був розроблений за підтримки волонтерської органіації All4Ukraine.",
        'footer_2' => "Всі права захищені",
        'footer_3' => "Наша сторінка Facebook",
        'add_bill_new' => "Перебити ставку",
        'add_bill_amount' => "Ставка (ціле число в гривні)",
        'add_bill_name' => "Ім`я",
        'add_bill_showname' => "   Показувати моє ім`я іншим учасникам",
        'add_bill_contact_1' => "   Контактні дані",
        'add_bill_contact_2' => "Для зв`язку з Вами якщо Ви виграєте аукціон",
        'add_bill_phone' => "Телефон:",
        'add_bill_close' => "Закрити",
        'subscribe' => "  Підписатись",


    );
    $en = array(
        'bid_sucess' => "The bet was accepted successfully",
        'bid_failed' => "Your rate is lower than the current rate",
        'site_title_1' => "We are raffling off a famous stamp with the author's signature",
        'site_title_2' => "Take part in a charity auction. Help the Armed Forces and get a stamp with the signature of the author of the famous phrase. All funds received will go towards the purchase of an",
        'site_title_3' => "ambulance for the medical service of the A7030 military unit.",
        'max_bid' => "Maximum rate: ",
        'make_a_bid' => "  Raise the rate",
        'bid' => "bid",
        'bids' => "bids",
        'bids_quont' => " has already been made!",
        'timer_1' => "Charity auction ends on:",
        'timer_2' => " days",
        'currency' => "USD",
        'history_1' => "Sir ",
        'hide' => "(hide)",
        'history_2' => " increased the rate as of:",
        'show_all' => "View all bids",
        'for_what_1' => "All funds from the charity auction will be reinvested for the medical service of the A7030 military unit 🙏 ❤️.",
        'for_what_2' => "<p>Every day, the Russian horde injures and kills hundreds of our compatriots.</p><p>The medical service saves not only military personnel, but also local residents.</p><p>Timely evacuation from the battlefield and providing first aid saves lives.</p><p>Medics are the guardian angels of our boys on the battlefield.</p>",
        'footer_1' => "The charity auction was developed with the support of the volunteer organization All4Ukraine.",
        'footer_2' => "All rights reserved",
        'footer_3' => "Our Facebook page",
        'add_bill_new' => "Break the bet",
        'add_bill_amount' => "Rate (whole number in UAH)",
        'add_bill_name' => "Name",
        'add_bill_showname' => "Show my name to other participants",
        'add_bill_contact_1' => " Contact details",
        'add_bill_contact_2' => "To contact you if you win the auction",
        'add_bill_phone' => "Phone:",
        'add_bill_close' => "Close",
        'subscribe' => "  Subscribe"
    );
?>
