<?php

    $ua = array(
        'bid_sucess1' => 'Ставка прийнята успішно 👏',
        'bid_sucess2' => 'Підписуйтесь на наш <strong><a href="https://t.me/all4ukraineua">Telegram-бот</a></strong> щоб отримувати оперативну інформацію про підвищення ставки',
        'bid_failed' => "Ваша ставка нижча за актуальну",
        'site_title_1' => "Прапор, підписаний у найпозитивнішого шеф-повара сучасності Євгена Клопотенка",
        'site_title_2' => "(латунь, висота 44см., діаметр 12 см.)",
        'site_title_3' => "<p>Ви ж пам'ятаєте, що саме з його подачі наш борщ став спадщиною ЮНЕСКО?</p>
                            <p>Так-от. Євген Клопотенко дуже оригінально підписав стяг - написав на ньому рецепт українських галушок!</p>
                            <p>Усі отримані кошти з аукціону будуть залучені на ",
        'site_title_4' => "покупку автівки для захисників з в/ч А0281</p>",
        'max_bid' => "Максимальна ставка: ",
        'make_a_bid' => "  Підняти ставку",
        'bid' => "ставки",
        'bids' => "ставок",
        'bids_quont' => " вже зроблено!",
        'timer_1' => "Благодійний аукціон закінчується через:",
        'timerStart_1' => "Благодійний аукціон починається через:",
        'timer_2' => " днів",
        'timer_end' => "Аукціон закінчено",
        'currency' => "грн.",
        'history_1' => "Добродій ",
        'hide' => "(прихований) ",
        'history_2' => " підвищив ставку станом на: ",
        'show_all' => "Переглянути всі ставки",
        'for_what_1' => "Усі отримані кошти з аукціону будуть залучені на покупку автівки для захисників з в/ч А0281",
        'for_what_2' => "<p>Автівка потрібна,  для виконання серйозних бойових завдань в складнопрохідній місцевості.</p>
                        <p>До речі, у військовослужбовця, який до нас звернувся, якраз нещодавно був день народження.</p>
                        <p>Давайте разом привітаємо нашого захисника та задонатимо на автівку для його підрозділу.</p>",
        'bid_history' => "Історія ставок станом на ",
        'footer_1' => "Платформа для благодійного аукціону була розроблена за підтримки волонтерської організації All4Ukraine.",
        'footer_2' => "Всі права захищені",
        'footer_3' => "Наша сторінка Facebook",
        'add_bill_new' => " Перебити ставку",
        'add_bill_amount' => "Ставка (ціле число в гривні)",
        'add_bill_name' => "Ім`я",
        'add_bill_showname' => "   Показувати моє ім`я іншим учасникам",
        'add_bill_contact_1' => "   Контактні дані",
        'add_bill_contact_2' => "Для зв`язку з Вами якщо Ви виграєте аукціон",
        'add_bill_phone' => "Телефон:",
        'add_bill_close' => "Закрити",
        'telegram' => "Підпишіться на наш телеграм-канал щоб миттєво отримувати інформацію по ставкам",
        'subscribe' => "  Підписатись",
        'copyright' => "Благодійний аукціон був розроблений за підтримки волонтерської органіації All4Ukraine.",
        'all_rules' => "Всі права захищені",
        'menu_conditions' => "Умови участі",
        'menu_history' => "Історія ставок",
        'menu_contacts' => "Контакти",
        'menu_lang' => "Мова, валюта",
        'cond_1' => "Умови участі",
        'cond_2' => "Виберіть розділ що вас цікавить або зв'яжіться з нами при необхідності",
        'cond_top_1' => "Умови участі в аукціоні",
        'cond_bottom_1' => "<ul> <li> Для того, щоб взяти участь в аукціоні потрібно зробити ставку та залишити контактні дані </li> <li> Аукціон триває до моменту його закінчення згідно таймеру на головній сторінці. Всі ставки, що були надані після закінчення аукціону - не будуть прийматись </li> <li> Переможцем благодійного аукціону вважається той, хто зробив найбільшу ставку. Якщо волонтерський фонд не зможе звязатись з переможцем аукціону протягом дня, переможцем вважається наступний кандидат згідно списку </li><li> Відправка лоту  відбувається за рахунок переможця і вибраним переможцем способом. Адже всі отримані за аукціон кошти підуть на закриття потреб ЗСУ </li> </ul>",
        'cond_top_2' => 'Про волонтерський фонд',
        'cond_bottom_2' => '<p>Волонтерський фонд був організований підприємцем <strong><a href="https://www.facebook.com/profile.php?id=100001783389284">Савченко Сергієм Олексієвичем</a></strong> на початку повномасштабного вторгнення росії на територію України.</p> <p>Інформацію про волонтерський фонд та команду фонду ви можете отримати <a href="https://www.facebook.com/all4ukraineua">на сайті фонду</a> та на нашій <a href="https://www.all4ukraine.org/">фейсбук сторінці</a>.</p>',
        'cond_top_3' => "Хто може бачити мої контактні дані",
        'cond_bottom_3' => "<p>Доступ до контактних даних є лише у представників волонтерської організації.</p> <p>Учасники аукціону можуть бачити личе імена інших учасників.</p> <p>При бажанні - ви можете приховати власне ім`я при піднятті ставки</p> <p>Контактні дані потрібні лише для підтвердження наміру взяти участь у аукціоні та для звязку з переможцем у випадку виграшу.</p>",
        'contacts_1' => "Волонтерський фонд All4Ukraine",
        'contacts_2' => "Офіційний сайт фонду:",
        'contacts_3' => "Телефон:",
        'contacts_4' => "Facebook:",
        'contacts_5' => "Instagram:",
        'contacts_6' => "Youtube:",
        'contacts_7' => "Tik-Tok:",
        'contacts_7' => "Tik-Tok:",
        'FBpage' => "Наша facebook сторінка ",
        'end' => "Аукціон завершено",

    );
    $en = array(
        'bid_sucess1' => 'Bid accepted successfully 👏',
        'bid_sucess2' => 'Subscribe to our <strong><a href="https://t.me/all4ukraineua">Telegram bot</a></strong> to receive instant information about raising the rate',
        'bid_failed' => "Your bid is lower than expected",
        'site_title_1' => "A flag of Ukraine, signed by the most positive modern chief cook Yevhen Klopotenko",
        'site_title_2' => "(brass, height 44 cm., diameter 12 cm.)",
        'site_title_3' => "<p>Do you remember that our Borscht became a heritage of UNESCO thanks to his presentation?</p>
                            <p>So here you go . Yevhen Klopotenko very originally signed a flag by writing on it the recipe for Ukrainian Halushky!</p>
                            <p>All the funds received will be donated to ",
        'site_title_4' => "the purchase of the vehicle for the defenders of the army unit A0281</p>",
        'max_bid' => "Max bet: ",
        'make_a_bid' => "  Raise bet",
        'bid' => "bids ",
        'bids' => "bids ",
        'bids_quont' => "already done!",
        'timer_1' => "Charity auction ends in:",
        'timerStart_1' => "Charity auction starts in:",
        'timer_2' => " days",
        'timer_end' => "Auction has ended",
        'currency' => "USD",
        'history_1' => "",
        'hide' => "(hidden)",
        'history_2' => " increased rate as of:",
        'show_all' => "View all bids",
        'for_what_1' => "All the funds received from the auction will go to the purchase of the vehicle for the defenders of the army unit A0281",
        'for_what_2' => "<p>The vehicle is necessary in order to perform serious combat assignments in hard to reach places.</p>
                        <p>By the way , the military person that contacted us recently had a birthday.</p>
                        <p>Let’s wish him happy late birthday to our defender and donate for the vehicle for his army unit.</p>",
        'bid_history' => "History of rates as of",
        'footer_1' => "The charity auction was developed with the support of the volunteer organization All4Ukraine.",
        'footer_2' => "All rights reserved",
        'footer_3' => "Our Facebook page",
        'add_bill_new' => " Break the bet",
        'add_bill_amount' => "Rate (whole number in USD)",
        'add_bill_name' => "Name",
        'add_bill_showname' => "Show my name to other participants",
        'add_bill_contact_1' => "Contact details",
        'add_bill_contact_2' => "To contact you if you win the auction",
        'add_bill_phone' => "Phone:",
        'add_bill_close' => "Close",
        'telegram' => "Subscribe to our Telegram channel to instantly receive information on rates",
        'subscribe' => "Subscribe",
        'copyright' => "The charity auction was developed with the support of the volunteer organization All4Ukraine.",
        'all_rules' => "All rights reserved",
        'menu_conditions' => "Conditions",
        'menu_history' => "Bet History",
        'menu_contacts' => "Contacts",
        'menu_lang' => "Language",
        'cond_1' => "Conditions of participation",
        'cond_2' => "Choose the section that interests you or contact us if necessary",
        'cond_top_1' => "Conditions for participation in the auction",
        'cond_bottom_1' => "<ul> <li> To participate in the auction, you need to make a bid and leave contact details </li> <li> The auction continues until its end according to the timer on the main page. All bids that were submitted after the end of the auction - will not be accepted </li> <li> The winner of the charity auction is the one who placed the highest bid. If the volunteer fund cannot contact the winner of the auction during the day - the winner is the next candidate according to the list </li><li> Sending the wining price is payed at the expense of the winner and in the way chosen by the winner. Because all the funds received during the auction will go to cover the needs of the Armed Forces of Ukraine </li> </ul>",
        'cond_top_2' => "About the volunteer fund",
        'cond_bottom_2' => '<p>The volunteer fund was organized by entrepreneur <strong><a href="https://www.facebook.com/profile.php?id=100001783389284">Serhiy Savchenko</a></strong> at the beginning of Russia`s full-scale invasion of the territories of Ukraine.</p> <p>You can get information about the volunteer fund and the fund`s team in our<a href="https://www.facebook.com/all4ukraineua">wesite</a> and in our <a href="https://www.all4ukraine.org/">facebook page</a>.</p>',
        'cond_top_3' => "Who can see my contact details",
        'cond_bottom_3' => '<p>Only representatives of the volunteer organization have access to contact information.</p> <p>For auction participants, access is open only to the name of the participants.</p> <p>If you wish, you can hide your own name when bidding</p> <p>Contact details are required to confirm your intention to win the auction and to contact the winner.</p>',
        'contacts_1' => "Volunteer fund All4Ukraine",
        'contacts_2' => "Official website of the fund:",
        'contacts_3' => "Phone:",
        'contacts_4' => "Facebook:",
        'contacts_5' => "Instagram:",
        'contacts_6' => "Youtube:",
        'contacts_7' => "Tik-Tok:",
        'FBpage' => "Our Facebook page",
        'end' => "Auction is over",
    );
?>
