<?php

    $ua = array(
        'bid_sucess1' => 'Ставка прийнята успішно 👏',
        'bid_sucess2' => 'Підписуйтесь на наш <strong><a href="https://t.me/all4ukraineua">Telegram-бот</a></strong> щоб отримувати оперативну інформацію про підвищення ставки',
        'bid_failed' => "Ваша ставка нижча за актуальну",
        'site_title_1' => "Комплект марок, підписаний Залужним",
        'site_title_2' => "(латунь, висота 44см., діаметр 12 см.)",
        'site_title_3' => "<p>Власником комплекту марок з легендарним підписом генерала Валерія Залужного стане той, хто запропонує найбільшу суму та сплатить її після завершення аукціону.</p><p>Усі отримані кошти з аукціону будуть залучені на ",
        'site_title_4' => "придбання дуже потужного бандероптаха  для захисників Донеччини.</p>",
        'max_bid' => "Максимальна ставка: ",
        'make_a_bid' => "  Підняти ставку",
        'bid' => "ставки",
        'bids' => "ставок",
        'bids_quont' => " вже зроблено!",
        'timer_1' => "Благодійний аукціон закінчується через:",
        'timer_2' => " днів",
        'timer_end' => "Аукціон закінчено",
        'currency' => "грн.",
        'history_1' => "Добродій ",
        'hide' => "(прихований) ",
        'history_2' => " підвищив ставку станом на: ",
        'show_all' => "Переглянути всі ставки",
        'for_what_1' => "Усі отримані кошти з аукціону будуть залучені на придбання дуже потужного бандероптаха  для захисників Донеччини",
        'for_what_2' => "<p>Ми продовжуємо збір коштів на бандероптаха для хлопців з військової частини А7222.</p>
                        <p>Військові кожного дня працюють над прекрасним проектом під назвою БАВОВНА. Для кращого виконання завдань у проекті 😉 нашим котикам потрібен дрон.</p>
                        <p>Хлопці натомість обіцяють багато бавовни 😉.</p>",
        'bid_history' => "Історія ставок станом на ",
        'footer_1' => "Платформа для благодійного аукціону була розроблена за підтримки волонтерської організації All4Ukraine.",
        'footer_2' => "Всі права захищені",
        'footer_3' => "Наша сторінка Facebook",
        'add_bill_new' => "Перебити ставку",
        'add_bill_amount' => "Ставка (ціле число в гривні)",
        'add_bill_name' => "Ім`я",
        'add_bill_showname' => "   Показувати моє ім`я іншим учасникам",
        'add_bill_contact_1' => "   Контактні дані",
        'add_bill_contact_2' => "Для зв`язку з Вами якщо Ви виграєте аукціон",
        'add_bill_phone' => "Телефон:",
        'add_bill_close' => "Закрити",
        'telegram' => "Підпишіться на наш телеграм-канал щоб миттєво отримувати інформацію по ставкам",
        'subscribe' => "  Підписатись",
        'copyright' => "Благодійний аукціон був розроблений за підтримки волонтерської органіації All4Ukraine.",
        'all_rules' => "Всі права захищені",
        'menu_conditions' => "Умови участі",
        'menu_history' => "Історія ставок",
        'menu_contacts' => "Контакти",
        'menu_lang' => "Мова, валюта",
        'cond_1' => "Умови участі",
        'cond_2' => "Виберіть розділ що вас цікавить або зв'яжіться з нами при необхідності",
        'cond_top_1' => "Умови участі в аукціоні",
        'cond_bottom_1' => "<ul> <li> Для того, щоб взяти участь в аукціоні потрібно зробити ставку та залишити контактні дані </li> <li> Аукціон триває до моменту його закінчення згідно таймеру на головній сторінці. Всі ставки, що були надані після закінчення аукціону - не будуть прийматись </li> <li> Переможцем благодійного аукціону вважається той, хто зробив найбільшу ставку. Якщо волонтерський фонд не зможе звязатись з переможцем аукціону протягом дня, переможцем вважається наступний кандидат згідно списку </li><li> Відправка лоту  відбувається за рахунок переможця і вибраним переможцем способом. Адже всі отримані за аукціон кошти підуть на закриття потреб ЗСУ </li> </ul>",
        'cond_top_2' => 'Про волонтерський фонд',
        'cond_bottom_2' => '<p>Волонтерський фонд був організований підприємцем <strong><a href="https://www.facebook.com/profile.php?id=100001783389284">Савченко Сергієм Олексієвичем</a></strong> на початку повномасштабного вторгнення росії на територію України.</p> <p>Інформацію про волонтерський фонд та команду фонду ви можете отримати <a href="https://www.facebook.com/all4ukraineua">на сайті фонду</a> та на нашій <a href="https://www.all4ukraine.org/">фейсбук сторінці</a>.</p>',
        'cond_top_3' => "Хто може бачити мої контактні дані",
        'cond_bottom_3' => "<p>Доступ до контактних даних є лише у представників волонтерської організації.</p> <p>Учасники аукціону можуть бачити личе імена інших учасників.</p> <p>При бажанні - ви можете приховати власне ім`я при піднятті ставки</p> <p>Контактні дані потрібні лише для підтвердження наміру взяти участь у аукціоні та для звязку з переможцем у випадку виграшу.</p>",
        'contacts_1' => "Волонтерський фонд All4Ukraine",
        'contacts_2' => "Офіційний сайт фонду:",
        'contacts_3' => "Телефон:",
        'contacts_4' => "Facebook:",
        'contacts_5' => "Instagram:",
        'contacts_6' => "Youtube:",
        'contacts_7' => "Tik-Tok:",
        'contacts_7' => "Tik-Tok:",
        'end' => "Аукціон завершено",

    );
    $en = array(
        'bid_sucess1' => 'Bid accepted successfully 👏',
        'bid_sucess2' => 'Subscribe to our <strong><a href="https://t.me/all4ukraineua">Telegram bot</a></strong> to receive instant information about raising the rate',
        'bid_failed' => "Your bid is lower than expected",
        'site_title_1' => "Charity auction for Ukrainian Armed Forces is announced open!",
        'site_title_2' => "(brass, height 44 cm., diameter 12 cm.)",
        'site_title_3' => "<p>The owner of the set of mailing stamps with a signature from a legendary general Valerii Zaluzhnyi will be the one who will offer the best price and pay it off at the end of the auction.</p>
<p>All the funds received from the auction will be given for",
        'site_title_4' => "the purchase of a very powerful «bird» for the defenders of Donetsk region</p>",
        'max_bid' => "Max bet: ",
        'make_a_bid' => "  Raise bet",
        'bid' => "bids ",
        'bids' => "bids ",
        'bids_quont' => "already done!",
        'timer_1' => "Charity auction ends in:",
        'timer_2' => " days",
        'timer_end' => "Auction has ended",
        'currency' => "USD",
        'history_1' => "",
        'hide' => "(hidden)",
        'history_2' => " increased rate as of:",
        'show_all' => "View all bids",
        'for_what_1' => "All the funds received from the auction will be given for the purchase of very important bird for the defenders of Donetsk region.",
        'for_what_2' => "<p>We continue to raise money for combat bird for the military unit А7222.</p>
                        <p>Our military is working every day under amazing project called “ Claps”. In order to better perform the army assignments 😉 our guys need a drone.</p>
                        <p>Guys promising us a lot of claps 😉.</p>",
        'bid_history' => "History of rates as of",
        'footer_1' => "The charity auction was developed with the support of the volunteer organization All4Ukraine.",
        'footer_2' => "All rights reserved",
        'footer_3' => "Our Facebook page",
        'add_bill_new' => " Break the bet",
        'add_bill_amount' => "Rate (whole number in USD)",
        'add_bill_name' => "Name",
        'add_bill_showname' => "Show my name to other participants",
        'add_bill_contact_1' => "Contact details",
        'add_bill_contact_2' => "To contact you if you win the auction",
        'add_bill_phone' => "Phone:",
        'add_bill_close' => "Close",
        'telegram' => "Subscribe to our Telegram channel to instantly receive information on rates",
        'subscribe' => "Subscribe",
        'copyright' => "The charity auction was developed with the support of the volunteer organization All4Ukraine.",
        'all_rules' => "All rights reserved",
        'menu_conditions' => "Conditions",
        'menu_history' => "Bet History",
        'menu_contacts' => "Contacts",
        'menu_lang' => "Language",
        'cond_1' => "Conditions of participation",
        'cond_2' => "Choose the section that interests you or contact us if necessary",
        'cond_top_1' => "Conditions for participation in the auction",
        'cond_bottom_1' => "<ul> <li> To participate in the auction, you need to make a bid and leave contact details </li> <li> The auction continues until its end according to the timer on the main page. All bids that were submitted after the end of the auction - will not be accepted </li> <li> The winner of the charity auction is the one who placed the highest bid. If the volunteer fund cannot contact the winner of the auction during the day - the winner is the next candidate according to the list </li><li> Sending the wining price is payed at the expense of the winner and in the way chosen by the winner. Because all the funds received during the auction will go to cover the needs of the Armed Forces of Ukraine </li> </ul>",
        'cond_top_2' => "About the volunteer fund",
        'cond_bottom_2' => '<p>The volunteer fund was organized by entrepreneur <strong><a href="https://www.facebook.com/profile.php?id=100001783389284">Serhiy Savchenko</a></strong> at the beginning of Russia`s full-scale invasion of the territories of Ukraine.</p> <p>You can get information about the volunteer fund and the fund`s team in our<a href="https://www.facebook.com/all4ukraineua">wesite</a> and in our <a href="https://www.all4ukraine.org/">facebook page</a>.</p>',
        'cond_top_3' => "Who can see my contact details",
        'cond_bottom_3' => '<p>Only representatives of the volunteer organization have access to contact information.</p> <p>For auction participants, access is open only to the name of the participants.</p> <p>If you wish, you can hide your own name when bidding</p> <p>Contact details are required to confirm your intention to win the auction and to contact the winner.</p>',
        'contacts_1' => "Volunteer fund All4Ukraine",
        'contacts_2' => "Official website of the fund:",
        'contacts_3' => "Phone:",
        'contacts_4' => "Facebook:",
        'contacts_5' => "Instagram:",
        'contacts_6' => "Youtube:",
        'contacts_7' => "Tik-Tok:",
        'FBpage' => "Our Facebook page",
        'end' => "Auction is over",
    );
?>
